# /*
# | --------------------------------------------------------------------------------------------------------
# | Filter scan files
# | --------------------------------------------------------------------------------------------------------
# /*
# | --------------------------------------------------------------------------------------------------------
# | Ignores all scanned files that being with the following string
# | beginsWith:
# |   - /tmp
# | will ignore all files that begin with /tmp, like "/tmp/analog/" and "/tmp/cache/"
beginsWith:
  - /.cagefs/
  - /quarantine_clamavconnector/
  - /tmp/analog/
# | --------------------------------------------------------------------------------------------------------
# | contains:
# |   - /updraft
# | ignores "/wp-content/plugins/updraft-plus/backups/*"
contains:

# | --------------------------------------------------------------------------------------------------------
# | endsWith:
# |   - .tar.gz
# | ignores "/public_html/backup.tar.gz
endsWith:
  - .apk
  - .wpress
  - .gz
  - .tgz
  - .tar.gz
  - .zip
  - .exe
# | --------------------------------------------------------------------------------------------------------
# | ignores any cPanel User names listed below
# | prohibitedcPanelUsers:
# |   - .jbm
# | ignores /home/.jbm/*
prohibitedcPanelUsers:
  - .jbm
  - solr
############################################################################################################
# /*
# | --------------------------------------------------------------------------------------------------------
# | Creates the Ticket Templates in the following directory
# | --------------------------------------------------------------------------------------------------------
# /*
outputDirectory: scanTickets
# | --------------------------------------------------------------------------------------------------------
# /*
# | --------------------------------------------------------------------------------------------------------
# | Whether the full path of the infected file should be used
# | If set to yes or on it will result in
# | /home/user/public_html/path/to/infected/file
# |
# | If set to no or off it will result in
# | /public_html/path/to/infected/file
# | --------------------------------------------------------------------------------------------------------
# /*
useFullPath: yes
# | --------------------------------------------------------------------------------------------------------
############################################################################################################
# /*
# | --------------------------------------------------------------------------------------------------------
# | Should Pastebin be used to avoid issues with clients that have a vast amount of infected files
# | --------------------------------------------------------------------------------------------------------
# /*
usePasteBin: yes
# | The max files that will be printed on text. If the files are more than ${maxScanFiles} a Pastebin URL will be created:
# | Keep it high to avoid daily usage limit
maxScanFiles: 30
# | This is the API Dev Key, it's obtained by logging in the Pastebin account and opening https://pastebin.com/api#1
apiDevKey: 
############################################################################################################

# /*
# | --------------------------------------------------------------------------------------------------------
# | Template strings to be replaced
# | --------------------------------------------------------------------------------------------------------
# /*
# | cPanelUserTemplateString:
# | replaces all occurrences of the value with the cPanel User Name or its Tickets that the ticket is being created for
cPanelUserTemplateString: INFECTED_USER_NAME
cPanelUserMalwareFilesString: INFECTED_USER_ALL_FILES