# /*
# | --------------------------------------------------------------------------------------------------------
# | Filter scan files
# | --------------------------------------------------------------------------------------------------------
# /*
# | Ignores all scanned files that being with the following string
# | Example:
# | beginsWith:
# |   - /tmp
# | will ignore all files that begin with /tmp, like "/tmp/analog/" and "/tmp/cache/"
beginsWith:
  - /.cagefs/
  - /quarantine_clamavconnector/
  - /tmp/analog/
# | contains:
# |   - /updraft
# | ignores "/wp-content/plugins/updraft-plus/backups/*"
contains:
# | endsWith:
# |   - .tar.gz
# | ignores "/public_html/backup.tar.gz
endsWith:
  - .apk
  - .wpress
  - .gz
  - .tgz
  - .tar.gz
  - .zip
  - .exe
############################################################################################################
# /*
# | --------------------------------------------------------------------------------------------------------
# | In what folder the template files should be created
# | --------------------------------------------------------------------------------------------------------
# /*
outputDirectory: scanTickets

useFullPath: yes
############################################################################################################
# /*
# | --------------------------------------------------------------------------------------------------------
# | Should Pastebin be used to avoid issues with clients that have a vast amount of infected files
# | --------------------------------------------------------------------------------------------------------
# /*
usePastebin: on
# | The max files that will be printed on text. If the files are more than ${maxScanFiles} a Pastebin URL will be created:
# | Keep it high to avoid daily usage limit
maxScanFiles: 30
# | This is the API Dev Key, it's obtained by logging in the Pastebin account and opening https://pastebin.com/api#1
apiDevKey: 
############################################################################################################